// 生成物:scripts/record-facts.mjs 从 public/engine/** 录的,升级 vendor 或重编引擎后重录,
// 不手改。每个游戏引擎运行时报出来的静态事实,申报(各 src/games/*.ts)对着它核。
export const facts = {
  net: {
    presets: [
      { name: '5x5', value: 0 },
      { name: '7x7', value: 1 },
      { name: '9x9', value: 2 },
      { name: '11x11', value: 3 },
      { name: '13x11', value: 4 },
      { name: '5x5 wrapping', value: 5 },
      { name: '7x7 wrapping', value: 6 },
      { name: '9x9 wrapping', value: 7 },
      { name: '11x11 wrapping', value: 8 },
      { name: '13x11 wrapping', value: 9 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '5' },
      { kind: 'string', label: 'Height', initial: '5' },
      { kind: 'boolean', label: 'Walls wrap around', initial: false },
      { kind: 'string', label: 'Barrier probability', initial: '0' },
      { kind: 'boolean', label: 'Ensure unique solution', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'unlocked-loops', kind: 'boolean', label: 'Highlight loops involving unlocked squares', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#acacac', '#737373', '#000000', '#0000ff', '#00ffff', '#ff0000', '#ff0000'],
    solvable: true,
  },
  cube: {
    presets: [
      { name: 'Cube', value: 0 },
      { name: 'Tetrahedron', value: 1 },
      { name: 'Octahedron', value: 2 },
      { name: 'Icosahedron', value: 3 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      {
        kind: 'choices',
        label: 'Type of solid',
        options: ['Tetrahedron', 'Cube', 'Octahedron', 'Icosahedron'],
        initial: 1,
      },
      { kind: 'string', label: 'Width / top', initial: '4' },
      { kind: 'string', label: 'Height / bottom', initial: '4' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#0000ff'],
    solvable: false,
  },
  fifteen: {
    presets: [
      { name: '4x4', value: 0 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '4' },
      { kind: 'string', label: 'Height', initial: '4' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'arrow-semantics',
        kind: 'choices',
        label: 'Sense of arrow keys',
        options: ['Move the tile', 'Move the gap'],
        initial: 0,
        optionKws: ['tile', 'gap'],
      },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ffffff', '#adadad'],
    solvable: true,
  },
  sixteen: {
    presets: [
      { name: '3x3', value: 0 },
      { name: '4x3', value: 1 },
      { name: '4x4', value: 2 },
      { name: '5x4', value: 3 },
      { name: '5x5', value: 4 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '4' },
      { kind: 'string', label: 'Height', initial: '4' },
      { kind: 'string', label: 'Number of shuffling moves', initial: '0' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ffffff', '#adadad'],
    solvable: true,
  },
  twiddle: {
    presets: [
      { name: '3x3 rows only', value: 0 },
      { name: '3x3 normal', value: 1 },
      { name: '3x3 orientable', value: 2 },
      { name: '4x4 normal', value: 3 },
      { name: '4x4 orientable', value: 4 },
      { name: '4x4, rotating 3x3 blocks', value: 5 },
      { name: '5x5, rotating 3x3 blocks', value: 6 },
      { name: '6x6, rotating 4x4 blocks', value: 7 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '3' },
      { kind: 'string', label: 'Height', initial: '3' },
      { kind: 'string', label: 'Rotating block size', initial: '2' },
      { kind: 'boolean', label: 'One number per row', initial: false },
      { kind: 'boolean', label: 'Orientation matters', initial: false },
      { kind: 'string', label: 'Number of shuffling moves', initial: '0' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ffffff', '#eaeaea', '#adadad', '#bfbfbf', '#d56a6a', '#804040'],
    solvable: true,
  },
  rect: {
    presets: [
      { name: '7x7', value: 0 },
      { name: '9x9', value: 1 },
      { name: '11x11', value: 2 },
      { name: '13x13', value: 3 },
      { name: '15x15', value: 4 },
      { name: '17x17', value: 5 },
      { name: '19x19', value: 6 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '7' },
      { kind: 'string', label: 'Height', initial: '7' },
      { kind: 'string', label: 'Expansion factor', initial: '0' },
      { kind: 'boolean', label: 'Ensure unique solution', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#acacac', '#000000', '#000000', '#737373', '#ff0000', '#3333ff', '#ff8080'],
    solvable: true,
  },
  netslide: {
    presets: [
      { name: '3x3 easy', value: 0 },
      { name: '3x3 medium', value: 1 },
      { name: '3x3 hard', value: 2 },
      { name: '4x4 easy', value: 3 },
      { name: '4x4 medium', value: 4 },
      { name: '4x4 hard', value: 5 },
      { name: '5x5 easy', value: 6 },
      { name: '5x5 medium', value: 7 },
      { name: '5x5 hard', value: 8 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '3' },
      { kind: 'string', label: 'Height', initial: '3' },
      { kind: 'boolean', label: 'Walls wrap around', initial: false },
      { kind: 'string', label: 'Barrier probability', initial: '1' },
      { kind: 'string', label: 'Number of shuffling moves', initial: '0' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#acacac', '#737373', '#000000', '#0000ff', '#00ffff', '#ff0000', '#b8b8b8', '#000000'],
    solvable: true,
  },
  pattern: {
    presets: [
      { name: '10x10', value: 0 },
      { name: '15x15', value: 1 },
      { name: '20x20', value: 2 },
      { name: '25x25', value: 3 },
      { name: '30x30', value: 4 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '15' },
      { kind: 'string', label: 'Height', initial: '15' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#ffffff', '#000000', '#000000', '#808080', '#4d4d4d', '#ff4040', '#ff0000', '#808080'],
    solvable: true,
  },
  solo: {
    presets: [
      { name: '2x2 Trivial', value: 0 },
      { name: '2x3 Basic', value: 1 },
      { name: '3x3 Trivial', value: 2 },
      { name: '3x3 Basic', value: 3 },
      { name: '3x3 Basic X', value: 4 },
      { name: '3x3 Intermediate', value: 5 },
      { name: '3x3 Advanced', value: 6 },
      { name: '3x3 Advanced X', value: 7 },
      { name: '3x3 Extreme', value: 8 },
      { name: '3x3 Unreasonable', value: 9 },
      { name: '3x3 Killer', value: 10 },
      { name: '9 Jigsaw Basic', value: 11 },
      { name: '9 Jigsaw Basic X', value: 12 },
      { name: '9 Jigsaw Advanced', value: 13 },
      { name: '3x4 Basic', value: 14 },
      { name: '4x4 Basic', value: 15 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Columns of sub-blocks', initial: '3' },
      { kind: 'string', label: 'Rows of sub-blocks', initial: '3' },
      { kind: 'boolean', label: '"X" (require every number in each main diagonal)', initial: false },
      { kind: 'boolean', label: 'Jigsaw (irregularly shaped sub-blocks)', initial: false },
      { kind: 'boolean', label: 'Killer (digit sums)', initial: false },
      {
        kind: 'choices',
        label: 'Symmetry',
        options: ['None', '2-way rotation', '4-way rotation', '2-way mirror', '2-way diagonal mirror', '4-way mirror', '4-way diagonal mirror', '8-way mirror'],
        initial: 1,
      },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Trivial', 'Basic', 'Intermediate', 'Advanced', 'Extreme', 'Unreasonable'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'pencil-keep-highlight', kind: 'boolean', label: 'Keep mouse highlight after changing a pencil mark', initial: false },
    ],
    keys: [
      { button: 49, label: '1' },
      { button: 50, label: '2' },
      { button: 51, label: '3' },
      { button: 52, label: '4' },
      { button: 53, label: '5' },
      { button: 54, label: '6' },
      { button: 55, label: '7' },
      { button: 56, label: '8' },
      { button: 57, label: '9' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#e6e6e6', '#cfcfcf', '#000000', '#000000', '#008a00', '#b3b3b3', '#ff0000', '#7373e6', '#737317'],
    solvable: true,
  },
  mines: {
    presets: [
      { name: '9x9, 10 mines', value: 0 },
      { name: '9x9, 35 mines', value: 1 },
      { name: '16x16, 40 mines', value: 2 },
      { name: '16x16, 99 mines', value: 3 },
      { name: '30x16, 99 mines', value: 4 },
      { name: '30x16, 170 mines', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '9' },
      { kind: 'string', label: 'Height', initial: '9' },
      { kind: 'string', label: 'Mines', initial: '10' },
      { kind: 'boolean', label: 'Ensure solubility', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#dadada', '#0000ff', '#008000', '#ff0000', '#000080', '#800000', '#008080', '#000000', '#808080', '#000000', '#ff0000', '#ff0000', '#ff0000', '#000000', '#000000', '#ffffff', '#999999', '#ff9999', '#ff8080'],
    solvable: true,
  },
  samegame: {
    presets: [
      { name: '5x5, 3 colours', value: 0 },
      { name: '10x5, 3 colours', value: 1 },
      { name: '15x10, 3 colours', value: 2 },
      { name: '15x10, 4 colours', value: 3 },
      { name: '20x15, 4 colours', value: 4 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '5' },
      { kind: 'string', label: 'Height', initial: '5' },
      { kind: 'string', label: 'No. of colours', initial: '3' },
      {
        kind: 'choices',
        label: 'Scoring system',
        options: ['(n-1)^2', '(n-2)^2'],
        initial: 1,
      },
      { kind: 'boolean', label: 'Ensure solubility', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#0000ff', '#008000', '#ff0000', '#b3b300', '#ff00ff', '#00cccc', '#8080ff', '#33cc33', '#ff8080', '#000000', '#ffffff', '#ffffff', '#adadad'],
    solvable: false,
  },
  flip: {
    presets: [
      { name: '3x3 Crosses', value: 0 },
      { name: '4x4 Crosses', value: 1 },
      { name: '5x5 Crosses', value: 2 },
      { name: '3x3 Random', value: 3 },
      { name: '4x4 Random', value: 4 },
      { name: '5x5 Random', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '5' },
      { kind: 'string', label: 'Height', initial: '5' },
      {
        kind: 'choices',
        label: 'Shape type',
        options: ['Crosses', 'Random'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#4c4c4c', '#ffffff', '#999999', '#999999', '#ff0000', '#cc0000'],
    solvable: true,
  },
  guess: {
    presets: [
      { name: 'Standard', value: 0 },
      { name: 'Super', value: 1 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Colours', initial: '6' },
      { kind: 'string', label: 'Pegs per guess', initial: '4' },
      { kind: 'string', label: 'Guesses', initial: '10' },
      { kind: 'boolean', label: 'Allow blanks', initial: false },
      { kind: 'boolean', label: 'Allow duplicates', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'show-labels', kind: 'boolean', label: 'Label colours with numbers', initial: false },
    ],
    keys: [],
    colours: ['#d4d4d4', '#000000', '#000000', '#80ffff', '#ff8080', '#8e8e8e', '#ff0000', '#ffff00', '#00ff00', '#334dff', '#ff8000', '#8000b3', '#804d4d', '#66ccff', '#b3ffb3', '#ff99ff', '#000000', '#ffffff'],
    solvable: true,
  },
  pegs: {
    presets: [
      { name: 'Cross 5x7', value: 0 },
      { name: 'Cross 7x7', value: 1 },
      { name: 'Cross 5x9', value: 2 },
      { name: 'Cross 7x9', value: 3 },
      { name: 'Cross 9x9', value: 4 },
      { name: 'Octagon', value: 5 },
      { name: 'Random 5x5', value: 6 },
      { name: 'Random 7x7', value: 7 },
      { name: 'Random 9x9', value: 8 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '7' },
      { kind: 'string', label: 'Height', initial: '7' },
      {
        kind: 'choices',
        label: 'Board type',
        options: ['Cross', 'Octagon', 'Random'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#ffffff', '#adadad', '#0000ff', '#8080ff'],
    solvable: false,
  },
  dominosa: {
    presets: [
      { name: 'Order 3, Trivial', value: 0 },
      { name: 'Order 4, Trivial', value: 1 },
      { name: 'Order 5, Trivial', value: 2 },
      { name: 'Order 6, Trivial', value: 3 },
      { name: 'Order 4, Basic', value: 4 },
      { name: 'Order 5, Basic', value: 5 },
      { name: 'Order 6, Basic', value: 6 },
      { name: 'Order 7, Basic', value: 7 },
      { name: 'Order 8, Basic', value: 8 },
      { name: 'Order 9, Basic', value: 9 },
      { name: 'Order 6, Hard', value: 10 },
      { name: 'Order 6, Extreme', value: 11 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Maximum number on dominoes', initial: '6' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Trivial', 'Basic', 'Hard', 'Extreme', 'Ambiguous'],
        initial: 1,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#000000', '#800000', '#ffffff', '#999999', '#d93333', '#4dd933'],
    solvable: true,
  },
  untangle: {
    presets: [
      { name: '6 points', value: 0 },
      { name: '10 points', value: 1 },
      { name: '15 points', value: 2 },
      { name: '20 points', value: 3 },
      { name: '25 points', value: 4 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Number of points', initial: '10' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'snap-to-grid', kind: 'boolean', label: 'Snap points to a grid', initial: false },
      { kw: 'show-crossed-edges', kind: 'boolean', label: 'Show edges that cross another edge', initial: false },
      {
        kw: 'vertex-style',
        kind: 'choices',
        label: 'Display style for vertices',
        options: ['Circles', 'Numbers'],
        initial: 0,
        optionKws: ['circle', 'number'],
      },
    ],
    keys: [],
    colours: ['#bbbbbb', '#e6e6e6', '#000000', '#ff0000', '#000000', '#0000ff', '#ffffff', '#808080', '#ff0000', '#808080', '#ffffff'],
    solvable: true,
  },
  blackbox: {
    presets: [
      { name: '5x5, 3 balls', value: 0 },
      { name: '8x8, 5 balls', value: 1 },
      { name: '8x8, 3-6 balls', value: 2 },
      { name: '10x10, 5 balls', value: 3 },
      { name: '10x10, 4-10 balls', value: 4 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      { kind: 'string', label: 'No. of balls', initial: '5' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#6a6a6a', '#959595', '#000000', '#00ff00', '#ffffff', '#adadad', '#bfbfbf', '#000000', '#ff0000', '#00ff00', '#ff0000'],
    solvable: true,
  },
  slant: {
    presets: [
      { name: '5x5 Easy', value: 0 },
      { name: '5x5 Hard', value: 1 },
      { name: '8x8 Easy', value: 2 },
      { name: '8x8 Hard', value: 3 },
      { name: '12x10 Easy', value: 4 },
      { name: '12x10 Hard', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Hard'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'left-button',
        kind: 'choices',
        label: 'Mouse button order',
        options: ['Left \\, right /', 'Left /, right \\'],
        initial: 0,
        optionKws: ['\\', '/'],
      },
      { kw: 'fade-grounded', kind: 'boolean', label: 'Fade grounded components', initial: false },
    ],
    keys: [],
    colours: ['#d5d5d5', '#959595', '#000000', '#000000', '#000000', '#ff0000', '#ffffff', '#d5d5d5', '#aaaaaa'],
    solvable: true,
  },
  lightup: {
    presets: [
      { name: '7x7 easy', value: 0 },
      { name: '7x7 tricky', value: 1 },
      { name: '7x7 hard', value: 2 },
      { name: '10x10 easy', value: 3 },
      { name: '10x10 tricky', value: 4 },
      { name: '10x10 hard', value: 5 },
      { name: '14x14 easy', value: 6 },
      { name: '14x14 tricky', value: 7 },
      { name: '14x14 hard', value: 8 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '7' },
      { kind: 'string', label: 'Height', initial: '7' },
      { kind: 'string', label: '%age of black squares', initial: '20' },
      {
        kind: 'choices',
        label: 'Symmetry',
        options: ['None', '2-way mirror', '2-way rotational', '4-way mirror', '4-way rotational'],
        initial: 4,
      },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky', 'Hard'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'show-lit-blobs', kind: 'boolean', label: 'Draw non-light marks even when lit', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#999999', '#000000', '#ffffff', '#ffff00', '#ff4040', '#737373'],
    solvable: true,
  },
  map: {
    presets: [
      { name: '20x15, 30 regions, Easy', value: 0 },
      { name: '20x15, 30 regions, Normal', value: 1 },
      { name: '20x15, 30 regions, Hard', value: 2 },
      { name: '20x15, 30 regions, Unreasonable', value: 3 },
      { name: '30x25, 75 regions, Normal', value: 4 },
      { name: '30x25, 75 regions, Hard', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '20' },
      { kind: 'string', label: 'Height', initial: '15' },
      { kind: 'string', label: 'Regions', initial: '30' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Normal', 'Hard', 'Unreasonable'],
        initial: 1,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'flash-type',
        kind: 'choices',
        label: 'Victory flash effect',
        options: ['Cyclic', 'Each to white', 'All to white'],
        initial: 0,
        optionKws: ['cyclic', 'each-white', 'all-white'],
      },
      { kw: 'show-numbers', kind: 'boolean', label: 'Number regions', initial: false },
      {
        kw: 'stipple-style',
        kind: 'choices',
        label: 'Display style for stipple marks',
        options: ['Small', 'Large'],
        initial: 0,
        optionKws: ['small', 'large'],
      },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#b38066', '#ccb366', '#809966', '#8c7359', '#ff0000', '#ffffff'],
    solvable: true,
  },
  loopy: {
    presets: [
      { name: '7x7 Squares - Easy', value: 0 },
      { name: '10x10 Squares - Easy', value: 1 },
      { name: '7x7 Squares - Normal', value: 2 },
      { name: '10x10 Squares - Normal', value: 3 },
      { name: '7x7 Squares - Hard', value: 4 },
      { name: '10x10 Squares - Hard', value: 5 },
      { name: '10x12 Triangular - Hard', value: 6 },
      { name: '7x7 Snub-Square - Hard', value: 7 },
      { name: '9x9 Cairo - Hard', value: 8 },
      { name: '5x5 Kites - Hard', value: 9 },
      { name: '10x10 Penrose (kite/dart) - Hard', value: 10 },
      { name: '10x10 Penrose (rhombs) - Hard', value: 11 },
      { name: '10x10 Honeycomb - Hard', value: 13 },
      { name: '4x5 Great-Hexagonal - Hard', value: 14 },
      { name: '4x5 Kagome - Hard', value: 15 },
      { name: '7x7 Octagonal - Hard', value: 16 },
      { name: '5x5 Floret - Hard', value: 17 },
      { name: '4x5 Dodecagonal - Hard', value: 18 },
      { name: '4x5 Great-Dodecagonal - Hard', value: 19 },
      { name: '3x5 Great-Great-Dodecagonal - Hard', value: 20 },
      { name: '4x5 Compass-Dodecagonal - Hard', value: 21 },
      { name: '10x10 Hats - Hard', value: 22 },
      { name: '10x10 Spectres - Hard', value: 23 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '10' },
      { kind: 'string', label: 'Height', initial: '10' },
      {
        kind: 'choices',
        label: 'Grid type',
        options: ['Squares', 'Triangular', 'Honeycomb', 'Snub-Square', 'Cairo', 'Great-Hexagonal', 'Octagonal', 'Kites', 'Floret', 'Dodecagonal', 'Great-Dodecagonal', 'Penrose (kite/dart)', 'Penrose (rhombs)', 'Great-Great-Dodecagonal', 'Kagome', 'Compass-Dodecagonal', 'Hats', 'Spectres'],
        initial: 0,
      },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Normal', 'Tricky', 'Hard'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'draw-faint-lines', kind: 'boolean', label: 'Draw excluded grid lines faintly', initial: true },
      {
        kw: 'auto-follow',
        kind: 'choices',
        label: 'Auto-follow unique paths of edges',
        options: ['No', 'Based on grid only', 'Based on grid and game state'],
        initial: 0,
        optionKws: ['off', 'fixed', 'adaptive'],
      },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#cfcf00', '#ffffff', '#ff0000', '#000000', '#cfcfcf'],
    solvable: true,
  },
  inertia: {
    presets: [
      { name: '10x8', value: 0 },
      { name: '15x12', value: 1 },
      { name: '20x16', value: 2 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '10' },
      { kind: 'string', label: 'Height', initial: '8' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ffffff', '#adadad', '#00ff00', '#ff0000', '#000000', '#99ffff', '#dfdfdf', '#ffff00'],
    solvable: true,
  },
  tents: {
    presets: [
      { name: '8x8 Easy', value: 0 },
      { name: '8x8 Tricky', value: 1 },
      { name: '10x10 Easy', value: 2 },
      { name: '10x10 Tricky', value: 3 },
      { name: '15x15 Easy', value: 4 },
      { name: '15x15 Tricky', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#b3ff80', '#996600', '#00b300', '#ccb300', '#ff0000', '#ffffff', '#990000'],
    solvable: true,
  },
  bridges: {
    presets: [
      { name: '7x7 easy', value: 0 },
      { name: '7x7 medium', value: 1 },
      { name: '7x7 hard', value: 2 },
      { name: '10x10 easy', value: 3 },
      { name: '10x10 medium', value: 4 },
      { name: '10x10 hard', value: 5 },
      { name: '15x15 easy', value: 6 },
      { name: '15x15 medium', value: 7 },
      { name: '15x15 hard', value: 8 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '7' },
      { kind: 'string', label: 'Height', initial: '7' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Medium', 'Hard'],
        initial: 0,
      },
      { kind: 'boolean', label: 'Allow loops', initial: true },
      {
        kind: 'choices',
        label: 'Max. bridges per direction',
        options: ['1', '2', '3', '4'],
        initial: 1,
      },
      {
        kind: 'choices',
        label: '%age of island squares',
        options: ['5%', '10%', '15%', '20%', '25%', '30%'],
        initial: 5,
      },
      {
        kind: 'choices',
        label: 'Expansion factor (%age)',
        options: ['0%', '10%', '20%', '30%', '40%', '50%', '60%', '70%', '80%', '90%', '100%'],
        initial: 1,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'show-hints', kind: 'boolean', label: 'Show possible bridge locations', initial: false },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ffffff', '#adadad', '#40ff40', '#ffffff', '#adadad', '#c1c1c1', '#ff4040', '#ffaaaa'],
    solvable: true,
  },
  unequal: {
    presets: [
      { name: 'Unequal: 4x4 Easy', value: 0 },
      { name: 'Unequal: 5x5 Easy', value: 1 },
      { name: 'Unequal: 5x5 Tricky', value: 2 },
      { name: 'Adjacent: 5x5 Tricky', value: 3 },
      { name: 'Unequal: 5x5 Extreme', value: 4 },
      { name: 'Unequal: 6x6 Easy', value: 5 },
      { name: 'Unequal: 6x6 Tricky', value: 6 },
      { name: 'Adjacent: 6x6 Tricky', value: 7 },
      { name: 'Unequal: 6x6 Extreme', value: 8 },
      { name: 'Unequal: 7x7 Tricky', value: 9 },
      { name: 'Adjacent: 7x7 Tricky', value: 10 },
      { name: 'Unequal: 7x7 Extreme', value: 11 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      {
        kind: 'choices',
        label: 'Mode',
        options: ['Unequal', 'Adjacent'],
        initial: 0,
      },
      { kind: 'string', label: 'Size (s*s)', initial: '4' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Trivial', 'Easy', 'Tricky', 'Extreme', 'Recursive'],
        initial: 1,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'pencil-keep-highlight', kind: 'boolean', label: 'Keep mouse highlight after changing a pencil mark', initial: false },
    ],
    keys: [
      { button: 49, label: '1' },
      { button: 50, label: '2' },
      { button: 51, label: '3' },
      { button: 52, label: '4' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#d5d5d5', '#808080', '#000000', '#008000', '#ff0000', '#6a6ad5', '#ffffff', '#adadad'],
    solvable: true,
  },
  galaxies: {
    presets: [
      { name: '7x7 Normal', value: 0 },
      { name: '7x7 Unreasonable', value: 1 },
      { name: '10x10 Normal', value: 2 },
      { name: '10x10 Unreasonable', value: 3 },
      { name: '15x15 Normal', value: 4 },
      { name: '15x15 Unreasonable', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '7' },
      { kind: 'string', label: 'Height', initial: '7' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Normal', 'Unreasonable'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#ffffff', '#404040', '#ffffff', '#000000', '#aaaaaa', '#000000', '#000000', '#ffaaaa'],
    solvable: true,
  },
  filling: {
    presets: [
      { name: '9x7', value: 0 },
      { name: '13x9', value: 1 },
      { name: '17x13', value: 2 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '13' },
      { kind: 'string', label: 'Height', initial: '9' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [
      { button: 49, label: '1' },
      { button: 50, label: '2' },
      { button: 51, label: '3' },
      { button: 52, label: '4' },
      { button: 53, label: '5' },
      { button: 54, label: '6' },
      { button: 55, label: '7' },
      { button: 56, label: '8' },
      { button: 57, label: '9' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#e6e6e6', '#000000', '#a1a1a1', '#cfcfcf', '#ffc3c3', '#008a00', '#737373'],
    solvable: true,
  },
  keen: {
    presets: [
      { name: '4x4 Easy', value: 0 },
      { name: '5x5 Easy', value: 1 },
      { name: '5x5 Easy, multiplication only', value: 2 },
      { name: '6x6 Easy', value: 3 },
      { name: '6x6 Normal', value: 4 },
      { name: '6x6 Normal, multiplication only', value: 5 },
      { name: '6x6 Hard', value: 6 },
      { name: '6x6 Extreme', value: 7 },
      { name: '6x6 Unreasonable', value: 8 },
      { name: '9x9 Normal', value: 9 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Grid size', initial: '6' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Normal', 'Hard', 'Extreme', 'Unreasonable'],
        initial: 1,
      },
      { kind: 'boolean', label: 'Multiplication only', initial: false },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'pencil-keep-highlight', kind: 'boolean', label: 'Keep mouse highlight after changing a pencil mark', initial: false },
    ],
    keys: [
      { button: 49, label: '1' },
      { button: 50, label: '2' },
      { button: 51, label: '3' },
      { button: 52, label: '4' },
      { button: 53, label: '5' },
      { button: 54, label: '6' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#e6e6e6', '#000000', '#008a00', '#b3b3b3', '#ff0000', '#7373e6'],
    solvable: true,
  },
  towers: {
    presets: [
      { name: '4x4 Easy', value: 0 },
      { name: '5x5 Easy', value: 1 },
      { name: '5x5 Hard', value: 2 },
      { name: '6x6 Easy', value: 3 },
      { name: '6x6 Hard', value: 4 },
      { name: '6x6 Extreme', value: 5 },
      { name: '6x6 Unreasonable', value: 6 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Grid size', initial: '5' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Hard', 'Extreme', 'Unreasonable'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'pencil-keep-highlight', kind: 'boolean', label: 'Keep mouse highlight after changing a pencil mark', initial: false },
      {
        kw: 'appearance',
        kind: 'choices',
        label: 'Puzzle appearance',
        options: ['2D', '3D'],
        initial: 1,
        optionKws: ['2d', '3d'],
      },
    ],
    keys: [
      { button: 49, label: '1' },
      { button: 50, label: '2' },
      { button: 51, label: '3' },
      { button: 52, label: '4' },
      { button: 53, label: '5' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#e6e6e6', '#000000', '#008a00', '#b3b3b3', '#ff0000', '#7373e6', '#999999'],
    solvable: true,
  },
  singles: {
    presets: [
      { name: '5x5 Easy', value: 0 },
      { name: '5x5 Tricky', value: 1 },
      { name: '6x6 Easy', value: 2 },
      { name: '6x6 Tricky', value: 3 },
      { name: '8x8 Easy', value: 4 },
      { name: '8x8 Tricky', value: 5 },
      { name: '10x10 Easy', value: 6 },
      { name: '10x10 Tricky', value: 7 },
      { name: '12x12 Easy', value: 8 },
      { name: '12x12 Tricky', value: 9 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '5' },
      { kind: 'string', label: 'Height', initial: '5' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'show-black-nums', kind: 'boolean', label: 'Show numbers on black squares', initial: false },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#bbbbbb', '#000000', '#ffffff', '#666666', '#bbbbbb', '#33cc00', '#ff0000'],
    solvable: true,
  },
  magnets: {
    presets: [
      { name: '6x5 Easy', value: 0 },
      { name: '6x5 Tricky', value: 1 },
      { name: '6x5 Tricky, strip clues', value: 2 },
      { name: '8x7 Easy', value: 3 },
      { name: '8x7 Tricky', value: 4 },
      { name: '8x7 Tricky, strip clues', value: 5 },
      { name: '10x9 Tricky', value: 6 },
      { name: '10x9 Tricky, strip clues', value: 7 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '6' },
      { kind: 'string', label: 'Height', initial: '5' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky'],
        initial: 1,
      },
      { kind: 'boolean', label: 'Strip clues', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#ffffff', '#adadad', '#000000', '#ff0000', '#e6e6e6', '#8e8e8e', '#1a991a', '#000000', '#cc0000', '#3333ff'],
    solvable: true,
  },
  signpost: {
    presets: [
      { name: '4x4', value: 0 },
      { name: '4x4, free ends', value: 1 },
      { name: '5x5', value: 2 },
      { name: '5x5, free ends', value: 3 },
      { name: '6x6', value: 4 },
      { name: '7x7', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '4' },
      { kind: 'string', label: 'Height', initial: '4' },
      { kind: 'boolean', label: 'Start and end in corners', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'flash-type',
        kind: 'choices',
        label: 'Victory rotation effect',
        options: ['Unidirectional', 'Meshing gears'],
        initial: 0,
        optionKws: ['unidirectional', 'gears'],
      },
    ],
    keys: [],
    colours: ['#d5d5d5', '#ffffff', '#adadad', '#a3a3a3', '#6a6a6a', '#ff0000', '#33ff33', '#000000', '#bfbfbf', '#000000', '#0000e6', '#b2b2f7', '#fefefe', '#fe9f7a', '#97fa97', '#7ffed3', '#9270da', '#fea400', '#86cdf9', '#fefe00', '#fecfbc', '#cbcd88', '#8bfcb5', '#88b7d7', '#c88a6d', '#c2b97d', '#c2e67d', '#fee65e', '#b2b2b2', '#b27055', '#6aaf6a', '#59b294', '#664e99', '#b27300', '#5e90ae', '#b2b200', '#b29183', '#8e8f60', '#61b07f', '#608096', '#8c614c', '#888157', '#88a157', '#b2a142', '#e5e5e5', '#e58f6d', '#88e188', '#72e5be', '#8464c4', '#e59400', '#79b9e0', '#e5e500', '#e5baa9', '#b6b87b', '#7de3a3', '#7ba5c1', '#b47c62', '#afa670', '#afcf70', '#e5cf54', '#e9e9e9', '#e9baa7', '#b6e7b6', '#aae9d4', '#b3a2d7', '#e9bc6a', '#add1e7', '#e9e96a', '#e9d2c8', '#d0d1ae', '#b0e8c5', '#aec6d6', '#ceafa1', '#cbc7a9', '#cbdda9', '#e9dd99'],
    solvable: true,
  },
  range: {
    presets: [
      { name: '9 x 6', value: 0 },
      { name: '12 x 8', value: 1 },
      { name: '13 x 9', value: 2 },
      { name: '16 x 11', value: 3 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '9' },
      { kind: 'string', label: 'Height', initial: '6' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'left-mouse-button',
        kind: 'choices',
        label: 'Mouse button order',
        options: ['Left to fill, right to dot', 'Left to dot, right to fill'],
        initial: 0,
        optionKws: ['fill', 'dot'],
      },
    ],
    keys: [],
    colours: ['#e6e6e6', '#000000', '#ff0000', '#bbbbbb'],
    solvable: true,
  },
  pearl: {
    presets: [
      { name: '6x6 Easy', value: 0 },
      { name: '6x6 Tricky', value: 1 },
      { name: '8x8 Easy', value: 2 },
      { name: '8x8 Tricky', value: 3 },
      { name: '10x10 Easy', value: 4 },
      { name: '10x10 Tricky', value: 5 },
      { name: '12x8 Easy', value: 6 },
      { name: '12x8 Tricky', value: 7 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky'],
        initial: 1,
      },
      { kind: 'boolean', label: 'Allow unsoluble', initial: false },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'appearance',
        kind: 'choices',
        label: 'Puzzle appearance',
        options: ['Traditional', 'Loopy-style'],
        initial: 0,
        optionKws: ['traditional', 'loopy'],
      },
    ],
    keys: [],
    colours: ['#d5d5d5', '#ffffff', '#adadad', '#000000', '#ffffff', '#ff0000', '#666666', '#ffffff', '#0000ff', '#ccccff'],
    solvable: true,
  },
  undead: {
    presets: [
      { name: '4x4 Easy', value: 0 },
      { name: '4x4 Normal', value: 1 },
      { name: '4x4 Tricky', value: 2 },
      { name: '5x5 Easy', value: 3 },
      { name: '5x5 Normal', value: 4 },
      { name: '5x5 Tricky', value: 5 },
      { name: '7x7 Easy', value: 6 },
      { name: '7x7 Normal', value: 7 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '4' },
      { kind: 'string', label: 'Height', initial: '4' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Normal', 'Tricky'],
        initial: 1,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      { kw: 'pencil-keep-highlight', kind: 'boolean', label: 'Keep mouse highlight after changing a pencil mark', initial: false },
      {
        kw: 'monsters',
        kind: 'choices',
        label: 'Monster representation',
        options: ['Pictures', 'Letters'],
        initial: 0,
        optionKws: ['pictures', 'letters'],
      },
      {
        kw: 'count-style',
        kind: 'choices',
        label: 'Monster count display',
        options: ['Total', 'Remaining', 'Placed/Total'],
        initial: 0,
        optionKws: ['total', 'remaining', 'placed-total'],
      },
    ],
    keys: [
      { button: 71, label: 'Ghost' },
      { button: 86, label: 'Vampire' },
      { button: 90, label: 'Zombie' },
      { button: 8, label: 'Clear' },
    ],
    colours: ['#e6e6e6', '#000000', '#000000', '#ff0000', '#b3b3b3', '#ffffff', '#73e6e6', '#73e673', '#e6cfcf', '#999999'],
    solvable: true,
  },
  unruly: {
    presets: [
      { name: '8x8 Trivial', value: 0 },
      { name: '8x8 Easy', value: 1 },
      { name: '8x8 Normal', value: 2 },
      { name: '10x10 Easy', value: 3 },
      { name: '10x10 Normal', value: 4 },
      { name: '14x14 Easy', value: 5 },
      { name: '14x14 Normal', value: 6 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      { kind: 'boolean', label: 'Unique rows and columns', initial: false },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Trivial', 'Easy', 'Normal'],
        initial: 0,
      },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#4d4d4d', '#808080', '#d4d4d4', '#ffffff', '#afafaf', '#333333', '#5e5e5e', '#090909', '#00b300', '#ff0000'],
    solvable: true,
  },
  flood: {
    presets: [
      { name: '12x12 Easy', value: 0 },
      { name: '12x12 Medium', value: 1 },
      { name: '12x12 Hard', value: 2 },
      { name: '16x16 Medium', value: 3 },
      { name: '16x16 Hard', value: 4 },
      { name: '12x12, 3 colours', value: 5 },
      { name: '12x12, 4 colours', value: 6 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '12' },
      { kind: 'string', label: 'Height', initial: '12' },
      { kind: 'string', label: 'Colours', initial: '6' },
      { kind: 'string', label: 'Extra moves permitted', initial: '5' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#d5d5d5', '#000000', '#ff0000', '#ffff00', '#00ff00', '#334dff', '#ff8000', '#8000b3', '#804d4d', '#66ccff', '#b3ffb3', '#ff99ff', '#ffffff', '#adadad'],
    solvable: true,
  },
  tracks: {
    presets: [
      { name: '8x8 Easy', value: 0 },
      { name: '8x8 Tricky', value: 1 },
      { name: '10x8 Easy', value: 2 },
      { name: '10x8 Tricky', value: 3 },
      { name: '10x10 Easy', value: 4 },
      { name: '10x10 Tricky', value: 5 },
      { name: '10x10 Hard', value: 6 },
      { name: '15x10 Easy', value: 7 },
      { name: '15x10 Tricky', value: 8 },
      { name: '15x15 Easy', value: 9 },
      { name: '15x15 Tricky', value: 10 },
      { name: '15x15 Hard', value: 11 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '8' },
      { kind: 'string', label: 'Height', initial: '8' },
      {
        kind: 'choices',
        label: 'Difficulty',
        options: ['Easy', 'Tricky', 'Hard'],
        initial: 1,
      },
      { kind: 'boolean', label: 'Disallow consecutive 1 clues', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#bbbbbb', '#d0d0d0', '#000000', '#4d4d4d', '#808080', '#000000', '#80661a', '#0000ff', '#ccccff', '#ff0000', '#ffffff', '#ffffff'],
    solvable: true,
  },
  palisade: {
    presets: [
      { name: '5 x 5, regions of size 5', value: 0 },
      { name: '8 x 6, regions of size 6', value: 1 },
      { name: '10 x 8, regions of size 8', value: 2 },
      { name: '15 x 12, regions of size 10', value: 3 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Width', initial: '5' },
      { kind: 'string', label: 'Height', initial: '5' },
      { kind: 'string', label: 'Region size', initial: '5' },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
      {
        kw: 'cursor-mode',
        kind: 'choices',
        label: 'Cursor mode',
        options: ['Half-grid', 'Full-grid'],
        initial: 0,
        optionKws: ['half', 'full'],
      },
      { kw: 'clear-complete-regions', kind: 'boolean', label: 'Automatically clear edges in completed regions', initial: false },
    ],
    keys: [],
    colours: ['#e6e6e6', '#bbbbbb', '#000000', '#cfcf00', '#cfcfcf', '#ff0000'],
    solvable: true,
  },
  mosaic: {
    presets: [
      { name: 'Size: 3x3', value: 0 },
      { name: 'Size: 5x5', value: 1 },
      { name: 'Size: 10x10', value: 2 },
      { name: 'Size: 15x15', value: 3 },
      { name: 'Size: 25x25', value: 4 },
      { name: 'Size: 50x50', value: 5 },
      { name: 'Custom...', value: -1 },
    ],
    configure: [
      { kind: 'string', label: 'Height', initial: '10' },
      { kind: 'string', label: 'Width', initial: '10' },
      { kind: 'boolean', label: 'Aggressive generation (longer)', initial: true },
    ],
    prefs: [
      { kw: 'one-key-shortcuts', kind: 'boolean', label: 'Keyboard shortcuts without Ctrl', initial: true },
    ],
    keys: [],
    colours: ['#e6e6e6', '#94c4be', '#006663', '#141414', '#ececec', '#646464', '#ff0000', '#ffc8c8'],
    solvable: true,
  },
} as const
